# Generated by Django 4.0.6 on 2022-07-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_notespts_options_consern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.PositiveSmallIntegerField(verbose_name='ST with teacher')),
                ('sst_reasoning', models.CharField(max_length=500, verbose_name='Why to SST?')),
                ('behavior_patterns', models.CharField(max_length=500, verbose_name='Primary behavior patterns')),
                ('behavior_quality', models.CharField(choices=[('C', 'A health, development, or academic issue (Care/Therapeutic)?'), ('G', 'A student pushing the school’s behavioral boundaries (Guidance and  Discipline)?'), ('S', 'A student having difficulty understanding how to integrate into the fabric of their class (Social Inclusion)?')], max_length=1, verbose_name='Qualify this behavior')),
                ('why_consern', models.CharField(max_length=500, verbose_name='Concern reasoning')),
                ('what_done', models.CharField(max_length=500, verbose_name='What done')),
                ('smal_done', models.CharField(max_length=500, verbose_name='What done small')),
                ('didnt_worked', models.CharField(max_length=500, verbose_name='Not worked')),
                ('worse', models.CharField(max_length=500, verbose_name='Worse')),
                ('response_level', models.CharField(max_length=500, verbose_name='Responce level')),
                ('other_info', models.CharField(max_length=500, verbose_name='Other info for SST')),
                ('estim_result', models.CharField(max_length=500, verbose_name='Estimate result')),
            ],
        ),
        migrations.AlterModelOptions(
            name='consern',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='consern',
            name='refers',
            field=models.CharField(choices=[('NO', 'No Referral'), ('R', 'Referral'), ('RES', 'Concern Resolved')], max_length=3, verbose_name='Referral'),
        ),
    ]
