# Generated by Django 4.0.6 on 2022-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_intake_alter_consern_options_alter_consern_refers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consern',
            name='consern_type',
            field=models.CharField(max_length=2000, verbose_name='Type of Concern'),
        ),
        migrations.AlterField(
            model_name='consern',
            name='st_responce',
            field=models.CharField(max_length=2000, verbose_name='Student Response'),
        ),
        migrations.AlterField(
            model_name='consern',
            name='strategy_used',
            field=models.CharField(max_length=2000, verbose_name='Strategies Used'),
        ),
        migrations.AlterField(
            model_name='consern',
            name='teach_comm',
            field=models.CharField(max_length=2000, verbose_name='Teacher Comments'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='behavior_patterns',
            field=models.CharField(max_length=2000, verbose_name='Primary behavior patterns'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='didnt_worked',
            field=models.CharField(max_length=2000, verbose_name='Not worked'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='estim_result',
            field=models.CharField(max_length=2000, verbose_name='Estimate result'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='other_info',
            field=models.CharField(max_length=2000, verbose_name='Other info for SST'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='response_level',
            field=models.CharField(max_length=2000, verbose_name='Responce level'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='smal_done',
            field=models.CharField(max_length=2000, verbose_name='What done small'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='sst_reasoning',
            field=models.CharField(max_length=2000, verbose_name='Why to SST?'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='what_done',
            field=models.CharField(max_length=2000, verbose_name='What done'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='why_consern',
            field=models.CharField(max_length=2000, verbose_name='Concern reasoning'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='worse',
            field=models.CharField(max_length=2000, verbose_name='Worse'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_conselor',
            field=models.BooleanField(default=False, verbose_name='Conselor role'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_sst',
            field=models.BooleanField(default=False, verbose_name='SST role'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Teacher role'),
        ),
        migrations.AlterField(
            model_name='notespts',
            name='note',
            field=models.CharField(max_length=2000),
        ),
    ]
