# Generated by Django 4.0.6 on 2022-07-30 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_consern_consern_type_alter_consern_st_responce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stud_intake', to='school.student'),
        ),
        migrations.AddField(
            model_name='intake',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
