# Generated by Django 4.0.6 on 2022-07-30 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_intake_student_intake_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='concern',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consern_intake', to='school.consern'),
        ),
    ]
