# Generated by Django 4.0.6 on 2022-07-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_intake_concern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='concern',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consern_intake', to='school.consern'),
        ),
    ]
