# Generated by Django 4.0.6 on 2022-07-31 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_intake_concern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('note', models.CharField(max_length=2000, verbose_name='Observation note')),
                ('sst', models.OneToOneField(limit_choices_to={'is_sst': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sst_observation', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_observation', to='school.student')),
                ('teacher', models.OneToOneField(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
