# Generated by Django 4.0.6 on 2022-07-31 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_observation_sst_alter_observation_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('suport_text', models.CharField(max_length=2000, verbose_name='Support text')),
                ('note', models.CharField(max_length=2000, verbose_name='Support note')),
                ('sst', models.ForeignKey(limit_choices_to={'is_sst': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sst_support', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_support', to='school.student')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
