# Generated by Django 4.0.6 on 2022-08-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_ocupationaltherapy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocupationaltherapy',
            old_name='student_ot',
            new_name='stud_ot',
        ),
    ]
