# Generated by Django 4.0.6 on 2022-08-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_speechtherapy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocupationaltherapy',
            name='stud_ot',
        ),
        migrations.RemoveField(
            model_name='speechtherapy',
            name='stud_st',
        ),
        migrations.AddField(
            model_name='ocupationaltherapy',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stud_ot', to='school.student'),
        ),
        migrations.AddField(
            model_name='speechtherapy',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stud_st', to='school.student'),
        ),
    ]
