# Generated by Django 4.0.6 on 2022-08-09 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_ocupationaltherapy_stud_ot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=10, verbose_name='personid')),
                ('grades', models.CharField(max_length=100, verbose_name='grades')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Users data',
            },
        ),
    ]
