# Generated by Django 4.0.6 on 2022-08-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_usersdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_conselor',
            field=models.BooleanField(default=False, verbose_name='Counselor role'),
        ),
        migrations.AlterField(
            model_name='speechtherapy',
            name='add_notes',
            field=models.CharField(help_text='Additional notes', max_length=2000, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='speechtherapy',
            name='scr_res',
            field=models.CharField(help_text='Screening Results / Recommendations', max_length=2000, verbose_name='Screening Results / Recommendations'),
        ),
        migrations.AlterField(
            model_name='speechtherapy',
            name='screen_date',
            field=models.DateField(help_text='Screen Speech Date', verbose_name='Screen Speech Date'),
        ),
    ]
