# Generated by Django 4.0.6 on 2022-08-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_myuser_is_conselor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notespts',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='school.student'),
        ),
    ]
