# Generated by Django 4.0.6 on 2022-08-12 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_notespts_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponceToSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Responce date')),
                ('intervention', models.CharField(max_length=2000)),
                ('note', models.CharField(max_length=2000)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responce_support', to='school.support')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
