# Generated by Django 4.0.6 on 2022-08-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_readingscreening'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingScreening',
        ),
    ]
