# Generated by Django 4.0.6 on 2022-08-13 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_delete_readingscreening'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen_type', models.CharField(choices=[('IND', 'Independent'), ('IST', 'Instructional'), ('FRS', 'Frustrational'), ('PPF', 'PP-Frustrational')], max_length=3, verbose_name='Screening type')),
                ('date_screen', models.DateField(verbose_name='Screen date')),
                ('errors_screen', models.CharField(max_length=2000, verbose_name='Decoding errors')),
                ('question_screen', models.CharField(max_length=2000, verbose_name='Comprehension questions')),
                ('notes', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Additional notes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reading', to='school.student')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_read_screen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_screen'],
            },
        ),
    ]
