# Generated by Django 4.0.6 on 2022-08-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_observation_concern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='concern',
        ),
    ]
