# Generated by Django 4.0.6 on 2022-10-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_student_siblings_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consern',
            name='consern_type',
            field=models.CharField(choices=[('A', 'Academic'), ('G', 'Guidance and Discipline'), ('S', 'Social Inclusion'), ('C', 'Care and Therapeutic')], max_length=1, verbose_name='Type of Concern'),
        ),
    ]
