# Generated by Django 4.0.6 on 2022-10-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1, verbose_name='Stream level'),
        ),
        migrations.AddField(
            model_name='stream',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_observations', to='school.observation', verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='stream',
            name='status',
            field=models.CharField(choices=[('CL', 'Closed'), ('PR', 'Proceeding'), ('OP', 'Open')], default='OP', max_length=2, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='stream',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_supports', to='school.support', verbose_name='Support'),
        ),
    ]
