# Generated by Django 4.0.6 on 2022-10-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_stream_level_stream_observation_stream_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['date_start']},
        ),
        migrations.AddField(
            model_name='stream',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Stream name'),
        ),
    ]
