# Generated by Django 4.0.6 on 2022-10-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_alter_stream_options_stream_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consern',
            name='consern_type',
        ),
    ]
