# Generated by Django 4.0.6 on 2022-11-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_stream_stream_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_next',
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.stream', verbose_name='Previous Stream'),
        ),
    ]
