# Generated by Django 4.0.6 on 2022-11-07 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_remove_stream_stream_next_stream_stream_prev'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplicitStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=2000, verbose_name='Implicit Strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='intake',
            name='concern',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='concern',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='concern',
        ),
        migrations.RemoveField(
            model_name='support',
            name='concern',
        ),
        migrations.DeleteModel(
            name='Consern',
        ),
    ]
