# Generated by Django 4.0.6 on 2022-11-07 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_implicitstrategy_remove_intake_concern_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implicitstrategy',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='ReviewMeetingNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_strategy', models.CharField(blank=True, max_length=2000, verbose_name='Other strategy')),
                ('notes', models.CharField(max_length=2000, verbose_name='Anectodal notes')),
                ('progress', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Progress')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_name', to='school.implicitstrategy')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.stream', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
