# Generated by Django 4.0.6 on 2022-11-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_alter_implicitstrategy_options_reviewmeetingnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmeetingnotes',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.stream', verbose_name='Stream review'),
        ),
        migrations.AlterField(
            model_name='reviewmeetingnotes',
            name='text_strategy',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Other strategy'),
        ),
    ]
