# Generated by Django 4.0.6 on 2022-11-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_alter_reviewmeetingnotes_stream_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewMeetingNotes',
            new_name='ReviewMeetingNote',
        ),
    ]
