# Generated by Django 4.0.6 on 2022-11-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_remove_reviewmeetingnote_strategy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='status',
        ),
    ]
