# Generated by Django 4.0.6 on 2022-11-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_remove_stream_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='status',
            field=models.CharField(choices=[('CL', 'Closed'), ('PR', 'Proceeding'), ('OP', 'Open')], default='OP', max_length=2, verbose_name='Status'),
        ),
    ]
