# Generated by Django 4.0.6 on 2022-11-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_stream_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmeetingnote',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_stream', to='school.stream', verbose_name='Stream review'),
        ),
    ]
