# Generated by Django 4.0.6 on 2022-11-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_alter_reviewmeetingnote_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmeetingnote',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_student', to='school.student'),
        ),
    ]
