# Generated by Django 4.0.6 on 2022-11-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_reviewmeetingnote_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_stream', to='school.stream', verbose_name='Previous Stream'),
        ),
    ]
