# Generated by Django 4.0.6 on 2022-11-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_alter_stream_options_alter_stream_stream_prev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='observation',
        ),
        migrations.AddField(
            model_name='observation',
            name='stream',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='sream_observation', to='school.stream'),
        ),
    ]
