# Generated by Django 4.0.6 on 2022-11-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0056_remove_stream_observation_observation_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='progress',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Progress'),
        ),
    ]
