# Generated by Django 4.0.6 on 2022-11-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_stream_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_prev',
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_stream', to='school.stream', verbose_name='Next stream'),
        ),
    ]
