# Generated by Django 4.0.6 on 2022-11-15 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_remove_stream_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['name', 'id']},
        ),
        migrations.RemoveField(
            model_name='stream',
            name='support',
        ),
        migrations.AddField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='support',
            name='stream',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='support_stream', to='school.stream'),
        ),
        migrations.AddField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
