# Generated by Django 4.0.6 on 2022-11-15 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_alter_stream_options_remove_stream_support_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=2000, verbose_name='Support')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='support',
            name='student',
        ),
        migrations.RemoveField(
            model_name='support',
            name='suport_text',
        ),
        migrations.AddField(
            model_name='support',
            name='support',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_name', to='school.supportname'),
        ),
    ]
