# Generated by Django 4.0.6 on 2022-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0061_supportname_remove_support_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='support',
        ),
        migrations.AddField(
            model_name='support',
            name='support',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='support_name', to='school.supportname'),
        ),
    ]
