# Generated by Django 4.0.6 on 2022-11-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0062_remove_support_support_support_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='support',
        ),
        migrations.AddField(
            model_name='support',
            name='support_text',
            field=models.ManyToManyField(blank=True, default=None, related_name='support_name', to='school.supportname'),
        ),
    ]
