# Generated by Django 4.0.6 on 2022-11-20 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0063_remove_support_support_support_support_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='sst',
            field=models.ForeignKey(default=None, limit_choices_to={'is_sst': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sst_support', to=settings.AUTH_USER_MODEL),
        ),
    ]
