# Generated by Django 4.0.6 on 2022-12-03 13:49

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0064_alter_support_sst'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to=school.models.image_directory_path),
        ),
    ]
